- name: Gather variables per solana network
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ solana_network | lower }}-defaults.yaml"

- name: sol validator setup
  become: true
  become_user: solana
  template:
    src: validator.j2
    dest: /home/solana/validator.sh
    owner: solana
    group: solana
    mode: "0755"

- name: setup sol.service
  become: true
  become_user: root
  template:
    src: sol.service.j2
    dest: /etc/systemd/system/sol.service
    owner: root
    group: root
    mode: "0755"

- name: copy restart.sh
  become: true
  become_user: solana
  template:
    src: restart.sh
    dest: /home/solana/restart.sh
    owner: solana
    group: solana
    mode: "0755"

- name: copy snapcheck.py
  become: true
  become_user: solana
  template:
    src: snapcheck.py
    dest: "{{ base_path }}/snapcheck.py"
    owner: solana
    group: solana

- name: copy snapshot-finder.py
  become: true
  become_user: solana
  template:
    src: snapshot-finder.py
    dest: "{{ base_path }}/snapshot-finder.py"
    owner: solana
    group: solana
